import Svg from '@/components/shared/svg';
import ToolTips from '@/components/shared/tooltips';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>AlexFull Brazil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="page-home-wrapper">
        <div className="home-hero-wrapper">
          <div className="home-hero-content">
            <h1>A FullStack App with Hygraph, Next.JS 13 & Apollo GraphQL</h1>
            <p>
              Featuring Hygraph, a Native GraphQL Headless CMS, GraphQL Code
              Generator, Awesome Custom Components, SCSS Auto Convert Pixel to
              REM/EM and much more.
            </p>
            <Link href={'/blog'} className="home-hero-cta">
              See in action
            </Link>
            <div className="home-hero-logos-wrapper">
              <ToolTips
                content="Learn More ->"
                position="top"
                offset={20}
                background={'var(--danger)'}
              >
                <a target={'_blank'} href="https://nextjs.org/">
                  <Svg
                    height={50}
                    color="var(--dark-blue)"
                    src="assets/logos/next.svg"
                  />
                </a>
              </ToolTips>
              <ToolTips
                content="Learn More ->"
                position="top"
                offset={20}
                background={'var(--danger)'}
              >
                <a target={'_blank'} href="https://hygraph.com/">
                  <Svg
                    color="var(--dark-blue)"
                    src="assets/logos/hygraph.svg"
                  />
                </a>
              </ToolTips>

              <ToolTips
                content="Learn More ->"
                position="top"
                offset={20}
                background={'var(--danger)'}
              >
                <a target={'_blank'} href="https://www.apollographql.com/">
                  <Svg
                    height={50}
                    color="var(--dark-blue)"
                    src="assets/logos/apollo.svg"
                  />
                </a>
              </ToolTips>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
