import Svg from '@/components/shared/svg';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>AlexFull Brazil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="page-home-wrapper">
        <div className="home-hero-wrapper">
          <div className="home-hero-content">
            <h1>A FullStack App with Hygraph, Next.JS & Apollo GraphQL</h1>
            <p>
              Featuring Instant GraphQL content APIs, Graph Code Generator,
              Custom Components, auto convert Pixel to REM/EM and much more.
            </p>
            <Link href={'/blog'} className="home-hero-cta">
              See in action
            </Link>
            <div className="home-hero-logos-wrapper">
              <Svg color="var(--dark-blue)" src="assets/logos/next.svg" />
              <Svg color="var(--dark-blue)" src="assets/logos/hygraph.svg" />
              <Svg color="var(--dark-blue)" src="assets/logos/apollo.svg" />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
